apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gin
  name: gin
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gin
  template:
    metadata:
      labels:
        app: gin
    spec:
      containers:
      - image: gcr.io/${PROJECT_ID}/nthu-chatbot-api:latest
        imagePullPolicy: Always
        name: nthu-chatbot-api
        resources:
          requests:
            memory: "512Mi"
            CPU: "250m"
          limits:
            memory: "512Mi"
            CPU: "250m"
        ports:
        - containerPort: 8080
        env:
        - name: TZ
          value: Asia/Taipei
